// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "Blinkin.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

Blinkin::Blinkin() : frc::Subsystem("Blinkin") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    colorController = RobotMap::blinkinBlinkin;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void Blinkin::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void Blinkin::Periodic() {
    // Put code here to be run every loop

}

void Blinkin::BlackColor(){
	colorController->Set(0.99);//black color is 0.99
}

void Blinkin::LightChasePattern1(){
	colorController->Set(0.01);//light chase pattern for color 1 is 0.01
}

void Blinkin::PulsingPattern2(){
	colorController->Set(0.27);//heartbeat fast pattern for color 2 is 0.27
}

void Blinkin::ColorWavesPattern1n2(){
	colorController->Set(0.53);//color waves pattern for color 1 and 2 is 0.53
}
// Put methods for controlling this subsystem
// here. Call these from Commands.

