// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include "WPILib.h"

class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	
	
	
	
	
	
	
	
	
	
	
	
	std::shared_ptr<frc::Joystick> gamepad;
	std::shared_ptr<frc::JoystickButton> pullArm;
	std::shared_ptr<frc::JoystickButton> swingArm;
	std::shared_ptr<frc::JoystickButton> elevatorScale4;
	std::shared_ptr<frc::JoystickButton> elevatorScale5;
	std::shared_ptr<frc::JoystickButton> elevatorScale6;
	std::shared_ptr<frc::JoystickButton> elevatorSwitch;
	std::shared_ptr<frc::Joystick> joy;
	std::shared_ptr<frc::JoystickButton> automaticIntake;
	std::shared_ptr<frc::JoystickButton> manualOuttake;
	std::shared_ptr<frc::JoystickButton> manualIntake;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	OI();

	//commands to call specific joysticks are made
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	std::shared_ptr<frc::Joystick> getJoy();
	std::shared_ptr<frc::Joystick> getGamepad();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};

#endif
